#!/bin/sh

### USAGE: before_script <base-folder> <travis-branch>

BUILD_DIR=$1

# Environment info
echo "# Environment info"
echo " - `php --version`"
echo " - `mysql --version`"
echo " - `pg_config --version`"
echo " - SQLite3 `sqlite3 -version`"
echo ""

# Fetch all dependencies
# TODO Replace with different composer.json variations

echo "Checking out installer@2.4"
git clone --depth=100 --quiet -b 2.4 git://github.com/silverstripe/silverstripe-installer.git $BUILD_DIR

echo "Checking out framework@2.4"
git clone --depth=100 --quiet -b 2.4 git://github.com/silverstripe/sapphire.git $BUILD_DIR/sapphire

# Copy setup files
cp ./tests/travis/_ss_environment.php $BUILD_DIR
cp ./tests/travis/_config.php $BUILD_DIR/mysite

# Copy actual project code into build directory (checked out by travis)
cp -r . $BUILD_DIR/tagfield

cd $BUILD_DIR
